// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDahVcQtMyY7o9j33uSQPO-i7Eybisc6UA',
    appId: '1:1055588240559:web:a140282ce2725dc507985a',
    messagingSenderId: '1055588240559',
    projectId: 'proj2-91053',
    authDomain: 'proj2-91053.firebaseapp.com',
    storageBucket: 'proj2-91053.appspot.com',
    measurementId: 'G-WX1DEL64H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdRyhLczNohLOG7umXvTwogwxFi0Vy2g',
    appId: '1:1055588240559:android:d02c05b71639dffb07985a',
    messagingSenderId: '1055588240559',
    projectId: 'proj2-91053',
    storageBucket: 'proj2-91053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVwnGQNdrVG59PF0s7NmkGXpWYWFcmUs',
    appId: '1:1055588240559:ios:e65380ca36651e1a07985a',
    messagingSenderId: '1055588240559',
    projectId: 'proj2-91053',
    storageBucket: 'proj2-91053.appspot.com',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVwnGQNdrVG59PF0s7NmkGXpWYWFcmUs',
    appId: '1:1055588240559:ios:e65380ca36651e1a07985a',
    messagingSenderId: '1055588240559',
    projectId: 'proj2-91053',
    storageBucket: 'proj2-91053.appspot.com',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDahVcQtMyY7o9j33uSQPO-i7Eybisc6UA',
    appId: '1:1055588240559:web:93ed032d441ba6c407985a',
    messagingSenderId: '1055588240559',
    projectId: 'proj2-91053',
    authDomain: 'proj2-91053.firebaseapp.com',
    storageBucket: 'proj2-91053.appspot.com',
    measurementId: 'G-72XX5LD40Z',
  );
}
